"""Initial Migration

Revision ID: 64104cc971d9
Revises: 
Create Date: 2022-11-20 06:59:05.817744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64104cc971d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('textReview', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('textReview')

    # ### end Alembic commands ###
